# Generated by Django 5.1.2 on 2025-01-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0004_subtask_description_subtask_name_task_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.task'),
            preserve_default=False,
        ),
    ]
