# Generated by Django 5.1.2 on 2025-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0005_subtask_belongs_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='level',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='description',
        ),
        migrations.AddField(
            model_name='subtask',
            name='context',
            field=models.CharField(default=-1, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='instruction',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='outputFormatInstruction',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
