# Generated by Django 5.1.2 on 2025-01-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0006_rename_level_subtask_step_remove_subtask_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('TOOL', 'Tool'), ('CODE', 'Code')], default='AGENT', max_length=12),
        ),
    ]
