# Generated by Django 5.1.2 on 2025-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0007_subtask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='codeblock',
            field=models.TextField(null=True),
        ),
    ]
