# Generated by Django 5.1.2 on 2025-01-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0008_subtask_codeblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='codeblock',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='type',
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=2048)),
                ('instruction', models.CharField(max_length=2048)),
                ('outputFormatInstruction', models.CharField(max_length=2048)),
                ('codeblock', models.TextField(null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.subtask')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.task')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.tool')),
            ],
        ),
    ]
