# Generated by Django 5.1.2 on 2025-01-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0010_remove_tool_belongs_to_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasktool',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.subtask'),
        ),
    ]
