# Generated by Django 5.1.2 on 2025-02-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0011_alter_subtasktool_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='current_step',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='subtask',
            name='current_step_status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default=1, max_length=24),
            preserve_default=False,
        ),
    ]
