# Generated by Django 5.1.2 on 2025-02-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0015_remove_tasklog_task_taskrun_tasklog_task_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='task',
            name='current_step_status',
        ),
        migrations.AddField(
            model_name='taskrun',
            name='current_step',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='current_step_status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default=1, max_length=24),
            preserve_default=False,
        ),
    ]
