# Generated by Django 5.1.2 on 2025-02-06 03:32

import agentoapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0016_remove_task_current_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeRepFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=agentoapp.models.user_directory_path)),
                ('Knowledge_rep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.knowledgerep')),
            ],
        ),
    ]
