# Generated by Django 5.1.2 on 2025-02-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0018_alter_knowledgerepfiles_knowledge_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='type',
            field=models.CharField(choices=[('TOOLSUBTASK', 'Tool Sub Task'), ('RAGSUBTASK', 'RAG Sub Task'), ('LOOPSUBTASK', 'Loop Sub Task')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
