# Generated by Django 5.1.2 on 2025-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0019_subtask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='type',
            field=models.CharField(choices=[('TOOL', 'Tool'), ('RAG', 'RAG'), ('LOOP', 'Loop')], max_length=20),
        ),
    ]
