# Generated by Django 5.1.2 on 2025-02-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0020_alter_subtask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasktool',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentoapp.subtask'),
        ),
        migrations.AlterField(
            model_name='subtasktool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentoapp.tool'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentoapp.taskrun'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentoapp.task'),
        ),
    ]
