# Generated by Django 5.1.2 on 2025-02-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0021_alter_subtasktool_subtask_alter_subtasktool_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='knowledgerep',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.knowledgerep'),
            preserve_default=False,
        ),
    ]
