# Generated by Django 5.1.2 on 2025-02-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0023_alter_subtask_knowledgerep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='knowledgerep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.knowledgerep'),
        ),
    ]
