# Generated by Django 5.1.2 on 2025-02-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0024_alter_subtask_knowledgerep'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='model',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
