# Generated by Django 5.1.6 on 2025-03-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0025_subtask_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgerep',
            name='associated_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.task'),
        ),
        migrations.AlterField(
            model_name='knowledgerep',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
