# Generated by Django 5.1.6 on 2025-03-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0026_knowledgerep_associated_task_alter_knowledgerep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgerep',
            name='associated_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agentoapp.task'),
        ),
    ]
