# Generated by Django 5.1.6 on 2025-03-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentoapp', '0030_alter_taskrun_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='knowledgerep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentoapp.knowledgerep'),
        ),
    ]
